# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: backend
    init: |
      cd /workspace/fh-waes/backend
      cp .env.example .env |
      composer install |
      php artisan key:generate 
    command: |
      ./vendor/bin/sail up -d
      php artisan serve
  - name: frontend
    init: |
      echo "Starte frontend"


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8081
    onOpen: open-browser
  - port: 8080
    onOpen: ignore
  - port: 80
    onOpen: open-browser

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - mohamedbenhida.laravel-intellisense
