tasks:
  - name: backend
    init: |
      cd /workspace/fh-waes/backend
      cp .env.example .env
      composer install
      php artisan key:generate
    command: |
      cd /workspace/fh-waes/backend
      ./vendor/bin/sail up -d
      php artisan migrate
      php artisan serve

  - name: frontend
    init: |
      cd /workspace/fh-waes/frontend
      npm i
    command: |
      npm install -g @vue/cli
      cd /workspace/fh-waes/frontend
      npm run serve


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8081 # PhpMyAdmin
    onOpen: open-browser
    visibility: public
  - port: 80
    onOpen: ignore
  - port: 3006
    onOpen: ignore
  - port: 8080 # Frontend
    onOpen: open-browser
    visibility: public
  - port: 8000 # Backend
    onOpen: open-browser
    visibility: public

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - mohamedbenhida.laravel-intellisense
    - felixfbecker.php-debug
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - mubaidr.vuejs-extension-pack
    - formulahendry.auto-close-tag
    - irongeek.vscode-env
