tasks:
  - name: backend
    init: |
      cd /workspace/fh-waes/backend
      cp .env.example .env |
      composer install |
      php artisan key:generate 
    command: |
      ./vendor/bin/sail up -d
      php artisan serve

  - name: frontend
    init: |
      cd /workspace/fh-waes/frontend
      npm i
    command: |
      npm run dev


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8081
    onOpen: open-browser
  - port: 8080
    onOpen: ignore
  - port: 80
    onOpen: ignore
  - port: 3000
    onOpen: open-browser
  - port: 8000
    onOpen: open-browser

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - mohamedbenhida.laravel-intellisense
