# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      ./vendor/bin/sail build |
    command: |
      ./vendor/bin/sail up


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8081
    onOpen: open-browser
  - port: 80
    onOpen: open-browser

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - mohamedbenhida.laravel-intellisense
